### ISSUE TITLE
Unsupported protocol

### ISSUE THREAD

**Issue by mingweiLIU** [timoore/vsgCs#2]
Hi, I built vsgCS under windows with visual studio 2022, and when I run the demo worldviewer with my ion token file, there comes out with no earth but blue empty space, the errors were: [TilesetContentManager.cpp] An unexpected error occurs when loading tile: Unsupported protocol, Warning: Error while creating tile provider: Unsupported protocol.

**Comment by timoore** [comment]
Hi,
Thanks for giving vsgCs a try! What world file were you trying to load? I have not seen this error, but I would guess that there's a problem with your installation of libcurl. How did you install libcurl? I used vcpkg, and I have installed:
```
curl:x64-windows
curl[schannel]:x64-windows
curl[ssl]:x64-windows
curl[sspi]:x64-windows
curl[winssl]:x64-windows
```
Do you think you have a good network connection to cesium.com? We might need to make some timeout values user-configurable.

-- Tim

**Comment by mingweiLIU** [comment]
Yeah, I built all the 3rd party libs vsgCs need （such complicated work though）including the curl, and the network connecting to cesium.com is ok since I apply the token from the website. Your answer sugests me

**Comment by timoore** [comment]
You've left issue open, so do you think that the network is not the problem? Are you accessing the network through a proxy? If so, it's possible that we need to do some additional configuration in libcurl. A good test would be to run the vsgpagedlod example from vsgExamples, which also uses libcurl.

**Comment by mingweiLIU** [comment]
There were some errors with libcurl and the example come with  “SSL peer certificate or SSH remote key was not OK”, I finally fixed it by adding  curl_easy_setopt(curl,CURLOPT_SSL_VERIFYPEER,false) in UrlAssetResponse::setCallbacks.

**Comment by timoore** [comment]
> There were some errors with libcurl and the example come with “SSL peer certificate or SSH remote key was not OK”, I finally fixed it by adding curl_easy_setopt(curl,CURLOPT_SSL_VERIFYPEER,false) in UrlAssetResponse::setCallbacks.

Glad you got it working! I can imagine what you did, but if make a pull request then I will merge it in.
