### ISSUE TITLE
TURBOJPEG_LIBRARY-NOTFOUND Build error 

### ISSUE THREAD

**Issue by robertosfield** [timoore/vsgCs#5]
I have updated to vsgCs master (0f1c1ad8825c0864d1a030424988440a6cbf1c3b) and did a clean cmake and make and most things compile cleanly but got an error:

make[2]: *** No rule to make target 'TURBOJPEG_LIBRARY-NOTFOUND', needed by 'bin/csclient'. Stop.
make[2]: *** No rule to make target 'TURBOJPEG_LIBRARY-NOTFOUND', needed by 'bin/worldviewer'. Stop.

I will now have a look into the CMake files to see what is going on.

**Comment by timoore** [comment]
Sigh. It's a new dependency of cesium-native, replacing stbi for loading jpeg. Supposedly it gives a big performance boost. If you pull cesium-native/master and update submodules, all will be well.

Cesium-native doesn't provide its own cmake packaging files, so I have to fake it in FindCesium.cmake.

**Comment by robertosfield** [comment]
I will update Cesium when I get back. Perhaps we can get them to adopt
cmake config install.

**Comment by robertosfield** [comment]
Have to wonder how much work it be to just write a 3D Tiles parser.

**Comment by timoore** [comment]
Update cesium-native to fix the problem.
